title = "This file maintains notifications to HitUP users"

[[tips]]
id = 'inform-color-theme'
message = """
  Do you know HitUP has
  <a target="_blank"
  href="https://github.com/wonderbeyond/HitUP/wiki/Dark-Theme-Support">
  color theme support</a> now?
  """
[tips.env_requires]
  version = ">=4.9.0"
  # stage = "development"
  # is_maintainer = true
  # web_extension = true
  media_min_width = 768  # window.innerWidth

[[tips]]
id = 'ask-rating-on-chrome-web-store'
message = """
  Hi, do you like HitUP ? Could you please
  <a target="_blank" href="https://chrome.google.com/webstore/detail/hitup-find-top-things/eiokaohkigpbonodjcbjpecbnccijkjb?ref=HitUP-usertips">
    give a rating on chrome web store
  </a>?
  """
[tips.env_requires]
  # stage = "development"
  # is_maintainer = true
  web_extension = true
  media_min_width = 768  # window.innerWidth
